---
keyWords:
    - "and"
    - "del"
    - "for"
    - "is"
    - "raise"
    - "assert"
    - "elif"
    - "from"
    - "lambda"
    - "break"
    - "else"
    - "global"
    - "not"
    - "try"
    - "class"
    - "except"
    - "if"
    - "or"
    - "while"
    - "continue"
    - "exec"
    - "import"
    - "pass"
    - "yield"
    - "def"
    - "finally"
    - "in"
    - "print"
    - "self"
    - "return"
    
...